## Ours
#python label.py -d="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Radiology_Report_Transformation/IUX-Ray_result_groundtruth.csv" -o="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Extracted_report/" -c="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/ckpt/chexbert.pth"
#python label.py -d="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Radiology_Report_Transformation/IUX-Ray_result_result.csv" -o="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Extracted_report/" -c="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/ckpt/chexbert.pth"
#python label.py -d="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Radiology_Report_Transformation/MIMIC-CXR_result_testset_groundtruth.csv" -o="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Extracted_report/" -c="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/ckpt/chexbert.pth"
#python label.py -d="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Radiology_Report_Transformation/MIMIC-CXR_result_testset_result.csv" -o="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Extracted_report/" -c="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/ckpt/chexbert.pth"


## R2Gen
#python label.py -d="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Radiology_Report_Transformation/r2gen_R2Gen_Reset_Target_groundtruth.csv" -o="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Extracted_report/" -c="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/ckpt/chexbert.pth"
#python label.py -d="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Radiology_Report_Transformation/r2gen_R2Gen_Reset_Target_result.csv" -o="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Extracted_report/" -c="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/ckpt/chexbert.pth"
#python label.py -d="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Radiology_Report_Transformation/r2gen_result_revise_mimic_groundtruth.csv" -o="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Extracted_report/" -c="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/ckpt/chexbert.pth"
#python label.py -d="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Radiology_Report_Transformation/r2gen_result_revise_mimic_result.csv" -o="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Extracted_report/" -c="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/ckpt/chexbert.pth"


## Cvt2
python label.py -d="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Radiology_Report_Transformation/cvt2_DistGen2_Reset_Target_groundtruth.csv" -o="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Extracted_report/" -c="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/ckpt/chexbert.pth"
python label.py -d="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Radiology_Report_Transformation/cvt2_DistGen2_Reset_Target_result.csv" -o="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Extracted_report/" -c="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/ckpt/chexbert.pth"
python label.py -d="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Radiology_Report_Transformation/cvt2_test_reports_cvt2_groundtruth.csv" -o="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Extracted_report/" -c="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/ckpt/chexbert.pth"
python label.py -d="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Radiology_Report_Transformation/cvt2_test_reports_cvt2_result.csv" -o="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/Extracted_report/" -c="/home/htihe/PycharmProjects/CIBMProject/CE_Metrics_Calculation/CheXbert-master/CheXbert-master/src/ckpt/chexbert.pth"

